version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adoptme-backend
    ports:
      - "3000:3000"  # host:container
    environment:
      - MONGO_URI=mongodb://mongo:27017/adoptme
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm start

  mongo:
    image: mongo:6
    container_name: adoptme-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
